### ISSUE TITLE
zc-problem-get(1) SEGFAULT on the latest OpenBSD snapshot

### ISSUE THREAD

**Issue by abiscuola** [abiscuola/zc#34]
zc-problem-get(1) started to segfault after the latest upgrade (done on May 7), it segfaults with:

```
#0  0x00000d00b2b03b5d in ?? () from /usr/local/libexec/zc/zcproblemget
#1  0x00000d03074dbc80 in Curl_client_write () from /usr/local/lib/libcurl.so.26.3
#2  0x00000d03074ef65d in Curl_readwrite () from /usr/local/lib/libcurl.so.26.3
#3  0x00000d03074f9241 in multi_runsingle () from /usr/local/lib/libcurl.so.26.3
#4  0x00000d03074f84bc in curl_multi_perform () from /usr/local/lib/libcurl.so.26.3
#5  0x00000d03074f11e3 in curl_easy_perform () from /usr/local/lib/libcurl.so.26.3
#6  0x00000d00b2b04846 in ?? () from /usr/local/libexec/zc/zcproblemget
#7  0x00000d00b2b02959 in ?? () from /usr/local/libexec/zc/zcproblemget
#8  0x00000d00b2b0213b in ?? () from /usr/local/libexec/zc/zcproblemget
#9  0x0000000000000000 in ?? ()
```
Reproducible by calling zc-problem-get(1) without any command, passing it a severity cause the program to not crash

**Comment by abiscuola** [comment]
Not reproducible, but I'm pretty sure the problem is fixed by ca7c4601ed9c8bce5a5b7d51ff8c73d7822af300
